#!/usr/bin/env python3
"""emit_veriloga.py — Compile Prolog topology facts into Verilog-A testbench."""

import argparse
import os
import sys

from parser import parse_prolog, parse_paths, validate_topology


def generate_testbench(facts, output_path, source='unknown'):
    binds = facts.get('binds', [])
    ops = facts.get('valid_operator', [])
    env = facts.get('env_state', [])
    gates = facts.get('operator_gate', [])

    cells = []
    for i, (op_name, paths_str) in enumerate(ops):
        paths = parse_paths(paths_str)
        p = next((pt for pt, pol in paths if pol == 'p'), None)
        pn = next((pt for pt, pol in paths if pol == 'pn'), None)
        cells.append({'idx': i, 'name': op_name, 'p': p, 'pn': pn})

    env_map = {port: v for port, v in env}

    lines = []
    lines.append('`include "constants.vams"')
    lines.append('`include "disciplines.vams"')
    lines.append(f'// Generated by netlister/emit_veriloga.py')
    lines.append(f'// Source: {os.path.basename(source)}')
    lines.append(f'module exo_mesh_{len(cells)}cell_tb();')
    lines.append('    electrical sigma_net, gnd;')
    for c in cells:
        lines.append(f'    electrical op_gate_{c["idx"]};')
    for c in cells:
        if c['p']:
            lines.append(f'    electrical env_p_{c["idx"]};')
        if c['pn']:
            lines.append(f'    electrical env_pn_{c["idx"]};')
    lines.append('    ground gnd;')
    lines.append('')
    lines.append('    sigma_source SIGMA_SRC(.out(sigma_net), .gnd(gnd));')
    lines.append('')
    for c in cells:
        lines.append(f'    electrical bus_node_{c["idx"]};')
    for c in cells:
        prev = 'sigma_net' if c['idx'] == 0 else f'bus_node_{c["idx"]-1}'
        lines.append(f'    lossy_bus_segment BUS{c["idx"]}(.in({prev}), .out(bus_node_{c["idx"]}), .gnd(gnd));')
    lines.append('')
    for c in cells:
        p_s = f'env_p_{c["idx"]}' if c['p'] else 'gnd'
        pn_s = f'env_pn_{c["idx"]}' if c['pn'] else 'gnd'
        lines.append(f'    exo_cell CELL_{c["idx"]}(')
        lines.append(f'        .sig(bus_node_{c["idx"]}), .port_p({p_s}), .port_pn({pn_s}),')
        lines.append(f'        .op_gate(op_gate_{c["idx"]}), .gnd(gnd)')
        lines.append(f'    );')
    lines.append('')
    lines.append('    analog begin')
    for c in cells:
        if c['p'] and c['p'] in env_map:
            lines.append(f'        V(env_p_{c["idx"]}, gnd) <+ {env_map[c["p"]]};')
        if c['pn'] and c['pn'] in env_map:
            lines.append(f'        V(env_pn_{c["idx"]}, gnd) <+ {env_map[c["pn"]]};')
    lines.append('    end')
    lines.append('endmodule')

    output = '\n'.join(lines)
    with open(output_path, 'w') as f:
        f.write(output)
    return output


def main():
    parser = argparse.ArgumentParser(description='Prolog -> Verilog-A Netlister')
    parser.add_argument('--spec', default='logic/prolog/examples/three_cell_mesh.pl')
    parser.add_argument('--output', default='veriloga/exo_mesh_tb.va')
    parser.add_argument('--validate-only', action='store_true')
    args = parser.parse_args()

    spec_path = args.spec
    if not os.path.isabs(spec_path):
        cwd_p = os.path.join(os.getcwd(), spec_path)
        script_p = os.path.join(os.path.dirname(__file__), spec_path)
        if os.path.exists(cwd_p):
            spec_path = os.path.abspath(cwd_p)
        elif os.path.exists(script_p):
            spec_path = os.path.abspath(script_p)
        else:
            print(f"ERROR: spec not found at {cwd_p} or {script_p}")
            sys.exit(1)

    facts = parse_prolog(spec_path)
    print(f"Parsed {len(facts)} fact types from {spec_path}")
    for k, v in facts.items():
        print(f"  {k}: {len(v)} facts")

    errors = validate_topology(facts)
    if errors:
        print("\nVALIDATION ERRORS:")
        for e in errors:
            print(f"  [FAIL] {e}")
        sys.exit(1)
    print("\n[PASS] Topology validation passed.")

    if args.validate_only:
        return

    out_path = args.output
    if not os.path.isabs(out_path):
        out_path = os.path.join(os.getcwd(), out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    generate_testbench(facts, out_path, source=spec_path)
    print(f"[PASS] Generated: {out_path}")


if __name__ == '__main__':
    main()
